layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

repository: eneim/personal-website

projects:
  sort_by: stars
  sort_by options:
    # - pushed
    - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
      - eneim.github.io
      - learn-docker
      - gintro

social_media:
  # behance: eneim
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: eneim
  # keybase: your_username
  linkedin: eneim
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: ene__im
  # unsplash: your_username
  # vk: your_username
  website: https://ene.im
  # youtube: your_username

topics:
  - name: Android
    web_url: https://github.com/topics/android
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/android/android.png

  - name: VueJS
    web_url: https://github.com/topics/vuejs
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/vue/vue.png

  - name: NodeJS
    web_url: https://github.com/topics/nodejs
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/nodejs/nodejs.png
